### PR TITLE
Beta 2 fixes

### PR DESCRIPTION
**Pull request by RandomShaper**

### CODE REVIEW

**Comment by AurL** [comment]
@RandomShaper Thanks for the updates
Here are a few feedbacks:
* The Sketchfab header is not visible anymore (even after restart)
* I tried to save the scene but I got an alert window "Unknown file format: glTF": does it mean that scenes cannot be saved ? or did I miss something ?
* It could be nice to have the archive size given either in the "Download" button or somewhere else in the model window.

It has not been tested on high DPI yet.

**Comment by RandomShaper** [comment]
1) I can't reproduce that. Can you send a screenshot?
3) The file size is obtained when the download is requested so it can't be known beforehand, unless there is some property about it in the model JSON. I've not been able to find such field.

**Comment by AurL** [comment]
image

I have also 
```
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
OPENING: D:/Sketchfab/godot-plugin (D:::Sketchfab::godot-plugin)
running cmdline: "D:\Desktop\godot.windows.opt.tools.64.exe" "--path" "D:/Sketchfab/godot-plugin" "--editor"
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
EditorSettings::_get - Warning, not found: interface/editor/display_scale
SCRIPT ERROR: _get_editor_scale: Invalid call. Nonexistent function 'has' in base 'EditorSettings'.
          At: res://addons/sketchfab/plugin.gd:55
ERROR: Object::get_meta: Condition ' !metadata.has(p_name) ' is true. returned: Variant()
   At: core\object.cpp:1025
SCRIPT ERROR: get_plugin_icon: Invalid operands 'Nil' and 'float' in operator '/'.
          At: res://addons/sketchfab/plugin.gd:26
ERROR: Object::get_meta: Condition ' !metadata.has(p_name) ' is true. returned: Variant()
   At: core\object.cpp:1025
SCRIPT ERROR: _enter_tree: Invalid operands 'Nil' and 'float' in operator '/'.
          At: res://addons/sketchfab/Main.gd:56
ERROR: Object::get_meta: Condition ' !metadata.has(p_name) ' is true. returned: Variant()
   At: core\object.cpp:1025
SCRIPT ERROR: _ready: Invalid operands 'Vector2' and 'Nil' in operator '*'.
          At: res://addons/sketchfab/Main.gd:61
erasing C:\Users\Sketchfab-VR-Laptop\AppData\Roaming/Godot/projects/godot-plugin-e5b32650bdb348f300125db67e29cd58/filesystem_update3
```
but I'm not sure if it's related

**Comment by RandomShaper** [comment]
Definitely helpful! PR updated with fixes.

**Comment by AurL** [comment]
Thanks, I'll test, merge and release a new version today.

**Comment by AurL** [comment]
@RandomShaper Sorry for being a bit laggy on this.
For the download size, in Unity plugin we request the link when the model page is shown and update the download button with the size that is parsed from the response.

Would it be possible to have this here too ?
Thanks

**Comment by RandomShaper** [comment]
Done!

**Comment by AurL** [comment]
Thanks, looks good 👍

**Comment by AurL** [comment]
@RandomShaper  Should we still tell the user to use the custom Godot build or is it fixed in official Godot releases ?

**Comment by AurL** [comment]
@RandomShaper Also, there are new feedbacks on the plugin (that have been tested on another machine):
- There are still UI issues on 4K screen:
sans titre

- in the login window, `User` textbox hint should be replaced by Email.

**Comment by RandomShaper** [comment]
Sadly, Godot 3.0.3 has not been released yet, so the custom build is still needed.

No problem in changing the placeholder text, but as long as I can log in with my username, maybe "User / E-mail" would be better. What do you think?

Regarding the UI issue, it seems the plugin isn't being able to determine the right editor scale. What are the settings for editor scale in that Godot installation? (You can find it in editor settings.)

**Pull request merged**
